[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Sword Coming <impish-clang-swell@duck.com>"]
edition = "2024"
publish = false
repository = "https://github.com/jscptman/network_top_to_down"

[workspace.dependencies]
tokio = "1.47.1"
